In [1]:
import numpy as np

In [4]:
a=np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]])

In [5]:
a

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

In [21]:
a[2:4,1:4]

array([[0, 6, 2],
       [6, 1, 5]])

In [23]:
arr=np.arange(1,37).reshape(6,6)

In [24]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [25]:
arr[2]

array([13, 14, 15, 16, 17, 18])

In [26]:
arr[2:3,0:6]

array([[13, 14, 15, 16, 17, 18]])

In [28]:
arr[4:5,0:6]

array([[25, 26, 27, 28, 29, 30]])

In [29]:
arr[4:5,:]

array([[25, 26, 27, 28, 29, 30]])

In [30]:
arr[4:5,]

array([[25, 26, 27, 28, 29, 30]])

In [31]:
arr[:,2] #for single column

array([ 3,  9, 15, 21, 27, 33])

In [34]:
arr[2:5,5:6] #gives 2d with colon

array([[18],
       [24],
       [30]])

In [35]:
arr[2:5,5]

array([18, 24, 30])

In [36]:
arr[2:5,-1] #gives vector without colon

array([18, 24, 30])

In [38]:
arr[:,::2] #forward

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [40]:
arr[:,::-2] #backward

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [41]:
arr[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [42]:
arr[0:5:2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [2]:
np.broadcast(all)

In [4]:
x=np.array([[1,2,3]])
print(x.shape)

(1, 3)


In [7]:
y=np.array([[4],[5]])
print(y.shape)

(2, 1)


In [10]:
x,y=np.broadcast_arrays(x,y)

In [11]:
x,y

(array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]]))

In [12]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [13]:
y

array([[4, 4, 4],
       [5, 5, 5]])

In [14]:
x+y

array([[5, 6, 7],
       [6, 7, 8]])