In [2]:
import numpy as np

In [3]:
data=np.random.randn(7,4)

In [4]:
data

array([[-1.35445897, -1.32043683, -1.57174913,  0.51971107],
       [-2.1120251 ,  0.16578196,  1.08721392, -0.01032918],
       [ 1.09995623,  1.17793833, -0.50469892, -0.28380804],
       [-0.85032285, -0.89696638,  0.8058443 , -0.87123869],
       [ 0.79169339,  0.37374778,  1.34054301,  0.57121664],
       [-0.56845088, -0.99888541,  0.00323505, -0.06862556],
       [ 0.1471236 , -0.35704111,  1.30104011, -1.49720482]])

In [32]:
names=np.array(["bob","joe","will","bob","will","joe","joe"])

In [33]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [34]:
names=="saad"

array([False, False, False, False, False, False, False])

In [35]:
names=="joe"

array([False,  True, False, False, False,  True,  True])

In [36]:
data>1 #without frames gives true false

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [37]:
#for exact values put frames and extract values which is true

In [38]:
data[data>1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27])

In [39]:
bol=np.array([True,False,False,False,False,True,False],dtype="bool")

In [40]:
data[bol]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23]])

In [41]:
names=np.array(["bob","joe","will","bob","will","joe","joe"])

In [42]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [43]:
names=="bob"

array([ True, False, False,  True, False, False, False])

In [44]:
condition=names!="bob"

In [45]:
data[condition]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [46]:
data[~condition]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [47]:
data[~condition,3]

array([ 3, 15])

In [48]:
data[condition,1:3]

array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [49]:
data=np.arange(28).reshape(7,4)
print(data)
print(condition)
data[condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [50]:
data=np.arange(28).reshape(7,4)
print(data)
print(condition)
data[~condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 1,  2],
       [13, 14]])

In [51]:
data=np.arange(28).reshape(7,4)
print(data)
print(condition)
data[~condition,1:4]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 1,  2,  3],
       [13, 14, 15]])

In [60]:
names=np.array(["bob","joe","will","bob","will","joe","joe"])
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [61]:
cond= (names=="bob") & (names=="joe")

In [62]:
print(cond)

[False False False False False False False]


In [63]:
cond= (names=="bob") & (names=="joe")


# fancy indexing

In [64]:
arr=np.empty((8,4))

In [65]:
for i in range(8):
    arr[i]=i

In [66]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [69]:
arr[[4,0,1,7]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [70]:
arr[[4,0,1,2],[2,3,0,1]]
#(4,2),(0,3),(1,0),(2,1)

array([4., 0., 1., 2.])

In [73]:
arr=np.arange(32).reshape(8,4)
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [74]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# transpose on an array

In [75]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [76]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [77]:
 st=[22,11,33,44,55,11,44,56,43]

In [79]:
a=set(st)

In [80]:
a

{11, 22, 33, 43, 44, 55, 56}

In [86]:
arr=np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [88]:
np.vsplit(arr,3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [89]:
np.hsplit(arr,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]